/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include<stdint.h>

int main(void)
{
	uint32_t *pClkCtrlReg =   (uint32_t*)0x40023830;
	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
	uint32_t *pPortDOutReg =  (uint32_t*)0x40020C14;


	*pClkCtrlReg |= ( 1 << 3);
	*pPortDModeReg &= ~( 1 << 25);
	*pPortDModeReg |= ( 1 << 24);
	*pPortDModeReg &= ~( 1 << 27);
		*pPortDModeReg |= ( 1 << 26);
		*pPortDModeReg &= ~( 1 << 29);
				*pPortDModeReg |= ( 1 << 28);
				*pPortDModeReg &= ~( 1 << 31);
						*pPortDModeReg |= ( 1 << 30);


    while(1){

    	*pPortDOutReg |= ( 1 << 12);
    	for(uint32_t i=0;i<1000000;i++);
    	*pPortDOutReg |= ( 1 << 13);
    	for(uint32_t i=0;i<1000000;i++);
    	*pPortDOutReg |= ( 1 << 14);
    	for(uint32_t i=0;i<1000000;i++);
    	*pPortDOutReg |= ( 1 << 15);

    	for(uint32_t i=0;i<5000000;i++);

    	*pPortDOutReg &= ~( 1 << 12);
    	for(uint32_t i=0;i<1000000;i++);
    	*pPortDOutReg &= ~( 1 << 13);
    	for(uint32_t i=0;i<1000000;i++);
    	*pPortDOutReg &= ~( 1 << 14);
    	for(uint32_t i=0;i<1000000;i++);
    	*pPortDOutReg &= ~( 1 << 15);

    	for(uint32_t i=0;i<1000000;i++);

    }
}
