/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



int main(void)
{1
	__asm volatile("LDR R1,=#0x20001000");
	__asm volatile("LDR R2,=#0x20001004");
	_
#if _asm volatile("LDR R0,[R1]");
	__asm volatile("LDR R1,[R2]");
	__asm volatile("ADD R0,R0,R1");
	__asm volatile("STR R0,[R2]");
#endif


	/*Example3: Using C Pointers and Assembly*/
	//Operands are referenced by a percent sign followed by a single digit,
	//where %0 refers to the first %1 to the second operand and so forth.

    /* Read the value present at pointer p2 in to p1 */
	int p1, *p2;

	p2 = (int*)0x20000008;

	__asm volatile("LDR %0,[%1]": "=r"(p1): "r"(p2));

	/*Practice*/
	int rel=0,var1=10,var2=20;
	__asm volatile("ADD %0,%1,%2":"=r"(rel):"r"(var1),"r"(var2));


	for(;;);
}
